
# Pytorch Basics
#### Today, we're going to learn about the basic pytorch operations that are used in data handling and model creation.

Colab link [here](https://colab.research.google.com/drive/1-Aq91EMnrDQDxnsfeORuN0KeKDyAQt1Q?usp=sharing)

In [ ]:
#import necessary module
import torch

# Tensors and tensor properties

Tensors are matricies that have n dimensions. This can be confusing at first but its easy to get the hang of it once we see a few examples.

Let's start by creating a tensor. There are several functions that allow us to do that.


*   `torch.tensor()`
*   `torch.zeros()`
*   `torch.ones()`
*   `torch.randn()`




In [ ]:
# creating a tensor can be done multiple ways

tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tensor2 = torch.zeros(4, 2)

tensor3 = torch.ones(1, 3)

tensor4 = torch.randn(2, 2, 2)

# can you tell what these tensors look like?

In [40]:
# run this cell to check if your guesses are correct

print(tensor1, '\n')
print(tensor2, '\n')
print(tensor3, '\n')
print(tensor4, '\n')

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]) 

tensor([[1., 1., 1.]]) 

tensor([[[ 0.1264,  0.2294],
         [-0.9029,  1.5924]],

        [[ 1.7528, -2.5850],
         [ 0.7688,  0.5188]]]) 



Since these tensors may be hard to understand, let's see a visual example. Images can be turned into tensors. A standard RGB image has 3 color channels and each pixel can have a value [0-255]. We can turn each color channel into a 2D matrix of RGB values. Three of these 2D matricies is a 3D tensor which stores all of the information in the image so that a model can learn to process it.


<img src='../images/image_tensor.png' width=50% height=50%>

# Tensor Properties

Now that we've learned to create tensors, let's learn how to get the properties of tensors we create.


Tensors have several properties, the ones this tutorial will cover are:

*   `dtype`
*   `shape`
*   `device`
*   `ndim`



In [41]:
# run this cell to see the results

print(tensor1.dtype, '\n')
print(tensor1.shape, '\n')
print(tensor1.device, '\n')
print(tensor1.ndim, '\n')

print('\n')

print(tensor4.dtype, '\n')
print(tensor4.shape, '\n')
print(tensor4.device, '\n')
print(tensor4.ndim, '\n')

torch.int64 

torch.Size([3, 3]) 

cpu 

2 



torch.float32 

torch.Size([2, 2, 2]) 

cpu 

3 



Let's break down the values we just got.

<br>

tensor1.dtype returned int64. This means each value in the tensor is of type int64.

The shape was [3, 3]. When we created the tensor, we created it with 3 lists consisting of three values each.

Cpu is the device the tensor is loaded on. The cpu is generally where data types are initially created and then transferred to other devices.

Finally, ndim is 2. The tensor is two dimensional.

<br>

Now, try to understand why the shape of tensor4 is [2, 2, 2], the dtype is float64 and why ndim is 3.

# Tensor Operations

Finally, the fun stuff. Let's see how we can manipulate tensors with mathematical operations.

<br>

We can use standard python operators to do elementwise operations. Note that tensors must be of the same size.

*   `+` &nbsp; &nbsp; &nbsp; addition
*   `-` &nbsp; &nbsp; &nbsp; subtraction
*   `*` &nbsp; &nbsp; &nbsp; multiplication
*   `/` &nbsp; &nbsp; &nbsp; division
*   `**` &nbsp; &nbsp; squaring

In [ ]:
# let's start with an easy example
tensor1 = torch.ones(2, 2)
tensor2 = torch.ones(2, 2)

print(tensor1 + tensor2)
print('\n')


# take a wild guess with this one
tensor3 = torch.randn(3, 3)
tensor4 = torch.zeros(3, 3)

print(tensor3 * tensor4)
print('\n')


# let's do a harder one
tensor5 = torch.randn(2, 3)
tensor6 = torch.randn(2, 3)

print(tensor5 ** tensor6) # this may lead to some unexpected results
print()

# curveball
tensor7 = torch.ones(4, 4)
print(tensor7 * 2)

tensor([[2., 2.],
        [2., 2.]])


tensor([[0., 0., -0.],
        [0., 0., 0.],
        [-0., -0., 0.]])


tensor([[   nan, 0.8837,    nan],
        [   nan,    nan,    nan]])

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


Tensors also take advantage of logical operators. Let's see a quick example.

In [ ]:
# before you run this code cell, guess what the output will be

print(tensor5 >= tensor6)

# Linear algebra

The power of tensors comes from the linear algebra, we can perform various linear algebra operations to manipulate them to our needs.

*  `torch.matmul(), @` &nbsp; &nbsp; &nbsp; matrix multiplication
*  `.transpose(), .T` &nbsp; &nbsp; &nbsp; matrix transposition
*  `torch.eye()` &nbsp; &nbsp; &nbsp; 2D identity tensor
* `torch.dot()` &nbsp; &nbsp; &nbsp; dot product between two 1D tensors

In [49]:
# these are a bit more complicated
# if you need to review matrix multiplication rules this is a good resource
# https://www.mathsisfun.com/algebra/matrix-multiplying.html


tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

tensor3 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# @ implicitly calls torch.matmul()
print(tensor1 @ tensor2)
print('\n')
print(torch.matmul(tensor1, tensor2))
print('\n')

# remember transposition rules
print(tensor3.transpose(0, 1)) # choose specific dimensions to transpose (mainly used with CNNs)
print('\n')
print(tensor3.T) # .T implicitly calls .transpose(-2, -1)
print('\n')

# how many dimensions will this last tensor have? how can you check?
tensor3 = torch.randn(3)
tensor4 = torch.randn(3)
print(torch.dot(tensor3, tensor4))
print('\n')


tensor([[19, 22],
        [43, 50]])


tensor([[19, 22],
        [43, 50]])


tensor([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]])


tensor([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]])


tensor(0.8440)




Tensor Reshaping

Transposing isn't the only way to reshape a matrix. Pytorch provides other functions for higher dimensional tensors. Let's check them out.

*  `.view()`
*  `.reshape()`
*  `.squeeze()`
*  `.unsqueeze()`
*  `.permute()`


In [63]:
# .view() reshapes a tensor from the original dimensions to a new specified one
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
print('Before .view()')
print(tensor1.shape)
print('\n')
print('After .view()')
print(tensor1.view(9))
print(tensor1.view(9).shape) # what do you notice?
print('\n')

# .reshape() is almost the same as .view but it is more leniant on what can be reshaped
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
print('Before .reshape()')
print(tensor1.shape)
print('\n')
print('Afer .reshape()')
print(tensor1.reshape(9))
print(tensor1.reshape(9).shape) # what do you notice?
print('\n')


# .squeeze() may be confusing at first, but take a look at the output
tensor3 = torch.ones(1, 3, 1, 5)
print(tensor3.shape)
print(tensor3.squeeze().shape) # what happened to the tensor after it was squeezed?
print(tensor3.squeeze(2).shape) # what about here?
print('\n')

# .unsqueeze() is the opposite of .squeeze()
tensor4 = torch.ones(2, 3)
print(tensor4.shape)
print(tensor4.unsqueeze(1).shape) # what changed?
print(tensor4.unsqueeze(0).shape)
print('\n')

# .permute reorders dimensions, its a more powerful transpose
tensor5 = torch.randn(2, 3, 4)
print(tensor5.shape)
print('.permute(0, 2, 1)')
print(tensor5.permute(0, 2, 1).shape)
print('.permute(0, -2, -1)')
print(tensor5.permute(0, -2, -1).shape) # notice anything strange? what do negative numbers mean? Think string slicing...



Before .view()
torch.Size([3, 3])


After .view()
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


Before .reshape()
torch.Size([3, 3])


Afer .reshape()
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


torch.Size([1, 3, 1, 5])
torch.Size([3, 5])
torch.Size([1, 3, 5])


torch.Size([2, 3])
torch.Size([2, 1, 3])
torch.Size([1, 2, 3])


torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
torch.Size([2, 3, 4])
